# .gitpod.yml (version corrigée)

# NOUVEAU : On spécifie une image qui inclut les outils PostgreSQL
image: gitpod/workspace-postgres

tasks:
  # SIMPLIFIÉ : Cette tâche ne fait plus que préparer la base de données.
  - name: Setup Database
    init: |
      gp ports await 5432
      createdb -h localhost -p 5432 -U gitpod -w postgres || echo "La base de données existe déjà."
    command:
      echo "Bienvenue dans l'espace de travail des Ruches ! Suivez les étapes du guide pour continuer."

ports:
  - port: 3000
    onOpen: open-preview
  - port: 5000
    onOpen: ignore
  - port: 5432
    onOpen: ignore